package com.example.fitapp.domain.entities

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "exercises")
data class ExerciseEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String,
    val category: String,
    val muscleGroup: String,
    val equipment: String,
    val difficulty: String,
    val description: String,
    val instructions: String,
    val iconName: String = ""
)

object ExerciseData {
    val exercises = listOf(
        ExerciseEntity(name = "Bench Press", category = "Strength", muscleGroup = "Chest", equipment = "Barbell", difficulty = "Intermediate", description = "Compound chest exercise performed lying on a bench", instructions = "1. Lie on bench, feet flat on floor\n2. Grip bar slightly wider than shoulder width\n3. Lower bar to chest\n4. Press back up to starting position", iconName = "fitness_center"),
        ExerciseEntity(name = "Squat", category = "Strength", muscleGroup = "Legs", equipment = "Barbell", difficulty = "Intermediate", description = "Fundamental lower body compound movement", instructions = "1. Place bar on upper back\n2. Stand with feet shoulder-width apart\n3. Lower body by bending knees and hips\n4. Keep chest up, back straight\n5. Return to standing", iconName = "fitness_center"),
        ExerciseEntity(name = "Deadlift", category = "Strength", muscleGroup = "Back", equipment = "Barbell", difficulty = "Advanced", description = "Full body compound lift from the floor", instructions = "1. Stand with feet hip-width, bar over midfoot\n2. Bend at hips and knees to grip bar\n3. Keep back flat, chest up\n4. Drive through heels to stand\n5. Lower with control", iconName = "fitness_center"),
        ExerciseEntity(name = "Pull Up", category = "Strength", muscleGroup = "Back", equipment = "Pull-up Bar", difficulty = "Intermediate", description = "Upper body pulling exercise using bodyweight", instructions = "1. Hang from bar with overhand grip\n2. Pull body up until chin passes bar\n3. Lower with control", iconName = "fitness_center"),
        ExerciseEntity(name = "Overhead Press", category = "Strength", muscleGroup = "Shoulders", equipment = "Barbell", difficulty = "Intermediate", description = "Standing overhead pressing movement", instructions = "1. Stand with bar at shoulder height\n2. Press bar overhead until arms straight\n3. Lower back to start position", iconName = "fitness_center"),
        ExerciseEntity(name = "Barbell Row", category = "Strength", muscleGroup = "Back", equipment = "Barbell", difficulty = "Intermediate", description = "Bent-over rowing movement for back", instructions = "1. Bend forward with flat back\n2. Pull bar to lower chest\n3. Squeeze shoulder blades\n4. Lower with control", iconName = "fitness_center"),
        ExerciseEntity(name = "Push Up", category = "Bodyweight", muscleGroup = "Chest", equipment = "None", difficulty = "Beginner", description = "Classic bodyweight chest exercise", instructions = "1. Start in plank position\n2. Lower body by bending elbows\n3. Push back up to starting position", iconName = "fitness_center"),
        ExerciseEntity(name = "Lunge", category = "Bodyweight", muscleGroup = "Legs", equipment = "None", difficulty = "Beginner", description = "Unilateral lower body exercise", instructions = "1. Step forward with one leg\n2. Lower back knee toward ground\n3. Push through front heel to return\n4. Alternate legs", iconName = "directions_run"),
        ExerciseEntity(name = "Plank", category = "Core", muscleGroup = "Abs", equipment = "None", difficulty = "Beginner", description = "Isometric core stabilization exercise", instructions = "1. Start in forearm plank position\n2. Keep body in straight line\n3. Engage core and glutes\n4. Hold for prescribed time", iconName = "accessibility_new"),
        ExerciseEntity(name = "Bicep Curl", category = "Strength", muscleGroup = "Arms", equipment = "Dumbbell", difficulty = "Beginner", description = "Isolation exercise for biceps", instructions = "1. Stand holding dumbbells at sides\n2. Curl weights toward shoulders\n3. Lower with control", iconName = "fitness_center"),
        ExerciseEntity(name = "Tricep Dip", category = "Bodyweight", muscleGroup = "Arms", equipment = "Dip Bar", difficulty = "Intermediate", description = "Compound pushing exercise for triceps", instructions = "1. Support body on parallel bars\n2. Lower body by bending elbows\n3. Push back up to starting position", iconName = "fitness_center"),
        ExerciseEntity(name = "Lat Pulldown", category = "Strength", muscleGroup = "Back", equipment = "Cable", difficulty = "Beginner", description = "Machine-based vertical pulling exercise", instructions = "1. Sit at machine, secure thighs\n2. Grip bar wide, palms forward\n3. Pull bar to upper chest\n4. Return with control", iconName = "fitness_center"),
        ExerciseEntity(name = "Leg Press", category = "Strength", muscleGroup = "Legs", equipment = "Machine", difficulty = "Beginner", description = "Machine-based leg pressing movement", instructions = "1. Sit in machine, feet shoulder-width on platform\n2. Push platform away extending legs\n3. Return with control without locking knees", iconName = "fitness_center"),
        ExerciseEntity(name = "Romanian Deadlift", category = "Strength", muscleGroup = "Legs", equipment = "Barbell", difficulty = "Intermediate", description = "Hip-hinge movement targeting hamstrings", instructions = "1. Stand holding bar at hip height\n2. Hinge at hips, slight knee bend\n3. Lower bar along legs\n4. Return by driving hips forward", iconName = "fitness_center"),
        ExerciseEntity(name = "Dumbbell Fly", category = "Strength", muscleGroup = "Chest", equipment = "Dumbbell", difficulty = "Intermediate", description = "Isolation exercise for chest", instructions = "1. Lie on bench holding dumbbells above chest\n2. Lower arms out to sides with slight bend\n3. Return to starting position squeezing chest", iconName = "fitness_center"),
        ExerciseEntity(name = "Lateral Raise", category = "Strength", muscleGroup = "Shoulders", equipment = "Dumbbell", difficulty = "Beginner", description = "Isolation exercise for lateral deltoids", instructions = "1. Stand holding dumbbells at sides\n2. Raise arms out to sides to shoulder height\n3. Lower with control", iconName = "fitness_center"),
        ExerciseEntity(name = "Russian Twist", category = "Core", muscleGroup = "Abs", equipment = "None", difficulty = "Beginner", description = "Rotational core exercise", instructions = "1. Sit with knees bent, lean back slightly\n2. Rotate torso side to side\n3. Keep core engaged throughout", iconName = "accessibility_new"),
        ExerciseEntity(name = "Mountain Climber", category = "Cardio", muscleGroup = "Full Body", equipment = "None", difficulty = "Beginner", description = "Dynamic full-body cardio exercise", instructions = "1. Start in plank position\n2. Drive knees toward chest alternating legs\n3. Maintain quick pace", iconName = "directions_run"),
        ExerciseEntity(name = "Burpee", category = "Cardio", muscleGroup = "Full Body", equipment = "None", difficulty = "Intermediate", description = "Full body explosive conditioning exercise", instructions = "1. Start standing\n2. Drop to squat, hands on floor\n3. Kick legs back to plank\n4. Return to squat, jump up", iconName = "directions_run"),
        ExerciseEntity(name = "Jump Rope", category = "Cardio", muscleGroup = "Full Body", equipment = "Rope", difficulty = "Beginner", description = "Cardiovascular endurance exercise", instructions = "1. Hold rope handles at hip height\n2. Swing rope over head, jump slightly\n3. Maintain steady rhythm", iconName = "directions_run"),
        ExerciseEntity(name = "Kettlebell Swing", category = "Strength", muscleGroup = "Full Body", equipment = "Kettlebell", difficulty = "Intermediate", description = "Hip-hinge ballistic exercise", instructions = "1. Stand with kettlebell slightly ahead\n2. Hinge at hips, grip handle\n3. Hike kettlebell back between legs\n4. Drive hips forward to swing to chest height", iconName = "fitness_center"),
        ExerciseEntity(name = "Calf Raise", category = "Strength", muscleGroup = "Legs", equipment = "None", difficulty = "Beginner", description = "Isolation exercise for calves", instructions = "1. Stand on edge of step\n2. Raise heels as high as possible\n3. Lower heels below step level", iconName = "fitness_center"),
        ExerciseEntity(name = "Face Pull", category = "Strength", muscleGroup = "Shoulders", equipment = "Cable", difficulty = "Beginner", description = "Rear deltoid and rotator cuff exercise", instructions = "1. Set cable at face height with rope\n2. Pull rope toward face, elbows out\n3. Squeeze shoulder blades, return with control", iconName = "fitness_center"),
        ExerciseEntity(name = "Hip Thrust", category = "Strength", muscleGroup = "Legs", equipment = "Barbell", difficulty = "Intermediate", description = "Glute-focused hip extension exercise", instructions = "1. Sit on floor, upper back against bench\n2. Place bar across hips\n3. Drive hips up squeezing glutes\n4. Lower with control", iconName = "fitness_center"),
        ExerciseEntity(name = "Crunch", category = "Core", muscleGroup = "Abs", equipment = "None", difficulty = "Beginner", description = "Basic abdominal flexion exercise", instructions = "1. Lie on back, knees bent\n2. Hands behind head\n3. Curl shoulders off ground\n4. Lower with control", iconName = "accessibility_new"),
        ExerciseEntity(name = "Dumbbell Shoulder Press", category = "Strength", muscleGroup = "Shoulders", equipment = "Dumbbell", difficulty = "Beginner", description = "Seated overhead pressing exercise", instructions = "1. Sit on bench with back support\n2. Hold dumbbells at shoulder height\n3. Press overhead until arms straight\n4. Lower with control", iconName = "fitness_center"),
        ExerciseEntity(name = "Incline Bench Press", category = "Strength", muscleGroup = "Chest", equipment = "Barbell", difficulty = "Intermediate", description = "Upper chest focused pressing exercise", instructions = "1. Lie on incline bench (30-45 deg)\n2. Grip bar at shoulder width\n3. Lower bar to upper chest\n4. Press up to lockout", iconName = "fitness_center"),
        ExerciseEntity(name = "Hammer Curl", category = "Strength", muscleGroup = "Arms", equipment = "Dumbbell", difficulty = "Beginner", description = "Bicep and brachialis isolation exercise", instructions = "1. Stand holding dumbbells, palms facing\n2. Curl weights keeping neutral grip\n3. Lower with control", iconName = "fitness_center"),
        ExerciseEntity(name = "Leg Curl", category = "Strength", muscleGroup = "Legs", equipment = "Machine", difficulty = "Beginner", description = "Hamstring isolation exercise", instructions = "1. Lie face down on leg curl machine\n2. Curl weight toward glutes\n3. Lower with control", iconName = "fitness_center"),
        ExerciseEntity(name = "Leg Extension", category = "Strength", muscleGroup = "Legs", equipment = "Machine", difficulty = "Beginner", description = "Quadriceps isolation exercise", instructions = "1. Sit in leg extension machine\n2. Extend legs until fully straight\n3. Lower with control", iconName = "fitness_center"),
        ExerciseEntity(name = "Dumbbell Lunge", category = "Strength", muscleGroup = "Legs", equipment = "Dumbbell", difficulty = "Intermediate", description = "Weighted unilateral lower body exercise", instructions = "1. Hold dumbbells at sides\n2. Step forward into lunge position\n3. Push through front heel to return\n4. Alternate legs", iconName = "directions_run"),
        ExerciseEntity(name = "Bicycle Crunch", category = "Core", muscleGroup = "Abs", equipment = "None", difficulty = "Intermediate", description = "Dynamic oblique and abdominal exercise", instructions = "1. Lie on back, hands behind head\n2. Bring elbow to opposite knee\n3. Pedal legs in bicycle motion", iconName = "accessibility_new"),
        ExerciseEntity(name = "Box Jump", category = "Plyometric", muscleGroup = "Legs", equipment = "Box", difficulty = "Advanced", description = "Explosive jumping exercise onto box", instructions = "1. Stand facing box, feet shoulder-width\n2. Lower into quarter squat\n3. Explosively jump onto box\n4. Step down and repeat", iconName = "directions_run"),
        ExerciseEntity(name = "Dips", category = "Bodyweight", muscleGroup = "Arms", equipment = "Dip Bar", difficulty = "Intermediate", description = "Tricep and chest bodyweight exercise", instructions = "1. Support body on parallel bars\n2. Lower body until upper arms parallel to ground\n3. Push back up to starting position", iconName = "fitness_center"),
        ExerciseEntity(name = "Chin Up", category = "Bodyweight", muscleGroup = "Back", equipment = "Pull-up Bar", difficulty = "Intermediate", description = "Bicep-focused pulling exercise", instructions = "1. Hang from bar with underhand grip\n2. Pull body up until chin passes bar\n3. Lower with control", iconName = "fitness_center"),
        ExerciseEntity(name = "Front Raise", category = "Strength", muscleGroup = "Shoulders", equipment = "Dumbbell", difficulty = "Beginner", description = "Anterior deltoid isolation exercise", instructions = "1. Stand holding dumbbells in front\n2. Raise arms forward to shoulder height\n3. Lower with control", iconName = "fitness_center"),
        ExerciseEntity(name = "Cable Fly", category = "Strength", muscleGroup = "Chest", equipment = "Cable", difficulty = "Intermediate", description = "Cable chest isolation exercise", instructions = "1. Stand between two cable stacks\n2. Bring handles together in front of chest\n3. Return with control under tension", iconName = "fitness_center"),
        ExerciseEntity(name = "Bulgarian Split Squat", category = "Strength", muscleGroup = "Legs", equipment = "Bench", difficulty = "Advanced", description = "Unilateral quad-dominant exercise", instructions = "1. Place back foot on bench behind\n2. Lower body by bending front knee\n3. Drive through front heel to stand", iconName = "fitness_center"),
        ExerciseEntity(name = "Skull Crusher", category = "Strength", muscleGroup = "Arms", equipment = "Barbell", difficulty = "Intermediate", description = "Tricep isolation exercise", instructions = "1. Lie on bench holding bar above head\n2. Lower bar toward forehead by bending elbows\n3. Extend arms back to starting position", iconName = "fitness_center"),
        ExerciseEntity(name = "Farmer Walk", category = "Strength", muscleGroup = "Full Body", equipment = "Dumbbell", difficulty = "Beginner", description = "Loaded carry for grip and core", instructions = "1. Hold heavy dumbbells at sides\n2. Walk forward maintaining upright posture\n3. Continue for prescribed distance", iconName = "directions_run"),
        ExerciseEntity(name = "Treadmill Run", category = "Cardio", muscleGroup = "Legs", equipment = "Treadmill", difficulty = "Beginner", description = "Indoor running for cardiovascular fitness", instructions = "1. Set desired speed and incline\n2. Run at comfortable pace\n3. Maintain proper running form", iconName = "directions_run"),
        ExerciseEntity(name = "Cycling", category = "Cardio", muscleGroup = "Legs", equipment = "Bike", difficulty = "Beginner", description = "Low-impact cardiovascular exercise", instructions = "1. Adjust seat and handlebar height\n2. Pedal at steady cadence\n3. Adjust resistance as needed", iconName = "directions_run"),
        ExerciseEntity(name = "Swimming", category = "Cardio", muscleGroup = "Full Body", equipment = "Pool", difficulty = "Intermediate", description = "Full body low-impact exercise", instructions = "1. Choose stroke (freestyle, breaststroke, etc.)\n2. Swim at steady pace\n3. Breathe rhythmically", iconName = "pool"),
        ExerciseEntity(name = "Yoga Flow", category = "Flexibility", muscleGroup = "Full Body", equipment = "Mat", difficulty = "Beginner", description = "Flowing sequence of yoga poses", instructions = "1. Start in mountain pose\n2. Flow through sun salutations\n3. Hold each pose for 3-5 breaths", iconName = "accessibility_new"),
        ExerciseEntity(name = "Wall Sit", category = "Bodyweight", muscleGroup = "Legs", equipment = "None", difficulty = "Beginner", description = "Isometric quadriceps exercise", instructions = "1. Lean against wall, slide down to 90 deg knees\n2. Hold position keeping back flat against wall\n3. Maintain for prescribed time", iconName = "fitness_center"),
        ExerciseEntity(name = "Glute Bridge", category = "Bodyweight", muscleGroup = "Legs", equipment = "None", difficulty = "Beginner", description = "Glute activation and strengthening", instructions = "1. Lie on back, knees bent\n2. Drive hips up squeezing glutes\n3. Hold briefly, lower with control", iconName = "fitness_center"),
        ExerciseEntity(name = "Good Morning", category = "Strength", muscleGroup = "Back", equipment = "Barbell", difficulty = "Intermediate", description = "Hip-hinge posterior chain exercise", instructions = "1. Place bar on upper back\n2. Hinge at hips, slight knee bend\n3. Lower torso toward parallel\n4. Return by driving hips forward", iconName = "fitness_center"),
        ExerciseEntity(name = "Pendlay Row", category = "Strength", muscleGroup = "Back", equipment = "Barbell", difficulty = "Advanced", description = "Explosive barbell row from dead stop", instructions = "1. Hinge forward with flat back\n2. Pull bar explosively to lower chest\n3. Return bar to floor each rep", iconName = "fitness_center"),
        ExerciseEntity(name = "Stretching Routine", category = "Flexibility", muscleGroup = "Full Body", equipment = "Mat", difficulty = "Beginner", description = "Full body static stretching", instructions = "1. Hold each stretch for 20-30 seconds\n2. Breathe deeply throughout\n3. Never stretch to pain", iconName = "accessibility_new"),
        ExerciseEntity(name = "Jump Squat", category = "Plyometric", muscleGroup = "Legs", equipment = "None", difficulty = "Intermediate", description = "Explosive squat variation", instructions = "1. Start in squat position\n2. Explosively jump upward\n3. Land softly, immediately lower into next squat", iconName = "directions_run")
    )
}
